### ISSUE TITLE
Create a simple graphics library in order to speed up prototyping and development of Menu Screens.

### ISSUE THREAD

**Issue by IridescentRose** [noche-x/PSP-Chat#3]
Add a basic graphics library and rendering tool in order to draw graphics and work with Textures and Sprites easily. Should have a render manager, font manager, Sprite and Texture class, alongside Vertex and other simple utilities.

**Comment by noche-x** [comment]
We already have a render library/namespace. But it needs some improvements. For example: More font utilities, a proper sprite/texture manager and a vertex utility.

**Comment by IridescentRose** [comment]
90% done. Just needs some sprites.
